language: php
php:
  - 7.1
  - 7.2
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer self-update
  - composer install -vvv
  - php vendor/bin/phpunit UnitTest TestHttpClient/TestAsyncClient.php
  - php vendor/bin/phpunit UnitTest TestHttpClient/TestHttpClient.php